### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by kizukawana** [kizukawana/protospace-35023#2]
https://protospace-35023.herokuapp.com/

**Comment by snkw-works** [comment]
@kizukawana さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
##### プロトタイプ一覧表示機能
- [ ] **プロトタイプ毎に、画像・プロトタイプ名・キャッチコピー・投稿者の名前の、4つの情報について表示できるよう修正しましょう**
現状、プロトタイプ名が正しく表示されておりません。
<img width="512" alt="スクリーンショット 2021-04-02 16 53 42" src="https://user-images.githubusercontent.com/54050089/113394946-159ea380-93d4-11eb-9c5a-3dbea25b6076.png">

##### プロトタイプ詳細表示機能

- [ ] **ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されるよう修正しましょう**
以下の画像は「春」というユーザーが投稿したプロトタイプですが、ログイン中の「夏」というユーザー名が表示されております。
<img width="589" alt="スクリーンショット 2021-04-02 16 55 43" src="https://user-images.githubusercontent.com/54050089/113395096-48e13280-93d4-11eb-81b8-d4a759e5c343.png">

##### プロトタイプ編集機能
- [ ] **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないよう修正しましょう**
現状、編集時に空欄がある状態で「保存する」ボタンを押すと、そのページに留まりますが、入力されていた内容が保持されず、そのまま内容を再度入力して「保存する」ボタンを押すとエラーが出てしまい、編集が完了できない状態です。

##### ユーザー詳細機能
- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
現状、プロトタイプ投稿者名とコメント投稿者名をクリックすると、エラー画面に遷移してしまいます。
<img width="1440" alt="スクリーンショット_2021-04-02_17_00_23" src="https://user-images.githubusercontent.com/54050089/113395604-12f07e00-93d5-11eb-8744-4d45d788b379.png">

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるよう修正しましょう**
現状、ユーザー詳細ページにて「そのユーザーが投稿したプロトタイプ」が表示されない状態です。

##### その他
- [ ] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できるよう修正しましょう**
現状、ログアウト状態のユーザーはプロトタイプ詳細ページが閲覧できない状態です。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by kizukawana** [comment]
確認ありがとうございます。

修正変更しました、確認お願いします。

**Comment by kizukawana** [comment]
修正ができていない箇所があったので、さらに修正変更しました。
確認の方お願いします。

https://protospace-35023.herokuapp.com/

**Comment by miyu-yamamoto** [comment]
@kizukawana さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
